INSERT INTO medios_pago (descripcion) VALUES
('Efectivo'),
('Santander'),
('Ciudad'),
('Mercado Pago'),
('Cuenta DNI');

INSERT INTO motivos_gasto (descripcion) VALUES
('American Express'),
('Autonomos'),
('Barraza'),
('Bierzo'),
('La Cabaña'),
('Cochera Alberto'),
('Cochera Cossio'),
('Cocherra Lope'),
('Contador'),
('Dulce Jardin'),
('Edesur'),
('Expensas Chaco'),
('Expensas Ercilla'),
('Expensas Olavarria'),
('Expensas Olavarria Cochera'),
('Ford'),
('Galpon'),
('Ilusiones'),
('Iva'),
('Jardin Velecito'),
('Leopardo'),
('Mastercard'),
('Mecánico'),
('Papelera'),
('Suipachense'),
('Swiss Medical'),
('Vep'),
('Visa');
